#!/bin/bash

source $HOME/devtools/share/common.sh

set_default_ip $CASH_IP

request_sudo

echo "Mounting cash $IP..." && sudo mount -t cifs //$IP/storage/crystal-cash /srv/cash -o username=tc,password=$PASSWORD && echo "OK" || echo "FAIL"
