#!/bin/bash

source $HOME/devtools/share/common.sh

IP=$1
if [ -z $IP ]
then
    IP=$RETAIL_IP
else
    shift
fi

sshpass -p "324012" ssh -o "StrictHostKeyChecking=no" root@$IP "tail -f /var/lib/jboss/standalone/log/server.log"
