#!/bin/bash

source $HOME/devtools/share/common.sh

IP=$1
if [ -z $IP ]
then
    IP=$CENTRUM_IP
else
    shift
fi

request_sudo

echo "Mounting centrum $IP..." && \
    echo "324012" | sudo sshfs -o password_stdin -o "StrictHostKeyChecking=no" -o allow_other root@$IP:/var/lib/jboss/standalone /srv/centrum && \
    echo "OK" || echo "FAIL"
