#!/bin/bash

source $HOME/devtools/share/common.sh

IP=$1
if [ -z $IP ]
then
    IP=$RETAIL_IP
else
    shift
fi

request_sudo

echo "Mounting retail $IP..." && \
    echo "324012" | sudo sshfs -o password_stdin -o "StrictHostKeyChecking=no" -o allow_other root@$IP:/var/lib/jboss/standalone /srv/retail && \
    echo "OK" || echo "FAIL"
